### ISSUE TITLE
Ensinar o Básico de Git para integrantes sem experiência.

### ISSUE THREAD

**Issue by jsb989** [jsb989/gestao_projetos_github#2]
# Problema
Alguns dos integrantes do projeto, não estão familiarizados com o GitHub. Portanto, precisamos ensiná-los os conceitos básicos.

# Soluções propostas
- [ ] Dar aulas síncronas pelo Google Meet
- [ ] Gravar vídeo aulas para eles
- [x] Encontrar, na internet, vídeos que resolvam esse problema.

**Comment by mirkolamberti** [comment]
A gente pode procurar vídeos na internet para que não haja perca de tempo para os integrantes que já conhecem Git.

**Comment by jvgalvao** [comment]
isso mesmo
